import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Pendente de Parede Boêmio",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa",
    description:
      "Pendente de parede boêmio feito à mão com corda de algodão natural",
    category: "wall-decor",
    featured: true,
  },
  {
    id: "2",
    name: "Conjunto de Suportes para Plantas",
    price: 45.99,
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b",
    description:
      "Conjunto de 2 suportes de plantas em macramê de tamanhos diferentes",
    category: "plant-hangers",
    featured: true,
  },
  {
    id: "3",
    name: "Cortina Decorativa",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92",
    description: "Cortina de macramê grande, perfeita para portas ou janelas",
    category: "curtains",
    featured: true,
  },
  {
    id: "4",
    name: "Apanhador de Sonhos",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519",
    description: "Apanhador de sonhos artesanal com miçangas de madeira",
    category: "accessories",
    featured: false,
  },
  {
    id: "5",
    name: "Caminho de Mesa",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1612966809104-cc562b23e2d3",
    description: "Caminho de mesa elegante em macramê para sua mesa de jantar",
    category: "table-decor",
    featured: false,
  },
  {
    id: "6",
    name: "Prateleira Suspensa",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1614594576535-b70d7d27b812",
    description: "Prateleira suspensa em macramê com plataforma de madeira",
    category: "shelves",
    featured: false,
  },
  {
    id: "7",
    name: "Capa de Almofada Decorativa",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1616486788371-62d930495c44",
    description: "Capa de almofada decorativa em macramê com franjas",
    category: "pillows",
    featured: false,
  },
  {
    id: "8",
    name: "Arco de Casamento",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92",
    description: "Arco de casamento em macramê grande para ocasiões especiais",
    category: "special-occasions",
    featured: false,
  },
];
